wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.19
    start_time: 1714636625
    t:
      1:
      - 1
      - 11
      4: 3.8.19
      5: 0.12.10
      6: 4.39.3
      8:
      - 1
      - 3
      - 5
accelerator:
  desc: null
  value: gpu
batch_size:
  desc: null
  value: 50
checkpoint:
  desc: null
  value: checkpoint3
gradient_clip_val:
  desc: null
  value: 1.0
lr:
  desc: null
  value: 3.0e-05
max_epochs:
  desc: null
  value: 10
max_len:
  desc: null
  value: 200
num_gpus:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 4
test_file:
  desc: null
  value: data/validation.tsv
train_file:
  desc: null
  value: data/train.tsv
