wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1714740999
    t:
      1:
      - 1
      - 11
      4: 3.8.19
      5: 0.12.10
      6: 4.39.3
      8:
      - 1
      - 3
      - 5
